### ISSUE TITLE
Disable directly release

### ISSUE THREAD

**Issue by KevinKoenigNormal** [shr3jn/fastlane-plugin-huawei_appgallery_connect#1]
Is it possible to prevent direct pushing via fastlane parameters but to release it from the download area (manually)?

**Comment by shr3jn** [comment]
Sure, I will add a date option to release the app on scheduled date.

**Comment by KevinKoenigNormal** [comment]
would it also be possible to just upload the app and release it via the web console?

**Comment by shr3jn** [comment]
Does appgallery provide manual release feature?

**Comment by KevinKoenigNormal** [comment]
I think if it is in download mode it can be released manually https://developer.huawei.com/consumer/en/service/hms/catalog/AGCConnectAPI.html?page=AGC_appGalleryConnect_PublishApi_PublishApp

**Comment by shr3jn** [comment]
I guess in download mode, it will just the download the apk file from own server. The release will not be manual.

**Comment by KevinKoenigNormal** [comment]
Would it be possible with the option Releasing the App by Phase?

**Comment by shr3jn** [comment]
Ok I will add that option.

**Comment by KevinKoenigNormal** [comment]
Thank you very much, sir.

**Comment by shr3jn** [comment]
I've added option for phase wise release. Please check the updated Fastfile for example.
