### ISSUE TITLE
Error uploading bundle

### ISSUE THREAD

**Issue by nmunozsi** [shr3jn/fastlane-plugin-huawei_appgallery_connect#12]
Hi

When I try to upload a bundle insted of a apk y get this error:

huawei_appgallery_connect_helper.rb:137:in `upload_app': [!] undefined method `[]' for nil:NilClass (NoMethodError)

When I upload manually the .aab file it works fine, when I use the plugin it fails.

I'm new to fastlane plugins, is there a way I can help you debug this issue?

Thanks!

**Comment by shr3jn** [comment]
I haven't tested app bundles yet. I will check and let you know.

**Comment by lefloh** [comment]
Uploading app bundles was added a few weeks ago: https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-upload-url_v2

The plugin needs to provide a `suffix` parameter.

https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/blob/aedc85b6d3850625a200b21ef273a970003242e8/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb#L82

**Comment by shr3jn** [comment]
Yes, I'm working on that, on my test it was throwing an error "Package name already exists" when uploading bundles. Let me test again and shall release an update.

**Comment by zkrige** [comment]
im looking forward to this - I need to automate our AGC deployments and we're using bundles

**Comment by coldfish** [comment]
any updates about uploading bundle?

**Comment by minkiapps** [comment]
@shr3jn what is the status of this? I can try to ask Huawei developers internally, since I am Huawei DTSE in Austria.

**Comment by shr3jn** [comment]
@minkiapps Huawei has said that the package name exists, but I've tried uploading apps with unique package name, apk works fine but there is an error with aab.

**Comment by minkiapps** [comment]
@shr3jn how can I test the aab upload?

**Comment by shr3jn** [comment]
Still receiving the same error. Uploaded a new app with unique package name.

{
    "ret": {
        "code": 204144662,
        "msg": "[cds]add apk failed, additional msg is [package name already exists]"
    }
}

@minkiapps I'm testing through POSTMAN. You can checkout the APIs on the docs and try using postman

**Comment by shr3jn** [comment]
@minkiapps Here's the link to the doc: https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/obtain_token

**Comment by minkiapps** [comment]
could you post an example curl?

**Comment by shr3jn** [comment]
there are around 4 API's you need to consume before you can actually submit the aab

**Comment by coldfish** [comment]
Did you change suffix parameter before uploading the bundle (AAB) file?

https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-upload_appfile

**Comment by shr3jn** [comment]
@coldfish yes i did change suffix to aab

**Comment by shr3jn** [comment]
**1. Get Access Token:**
POST https://connect-api.cloud.huawei.com/api/oauth2/v1/token
Body:
`{"client_id":"XXX", "grant_type":"client_credentials","client_secret":"XXX"}`

2. Get Upload URL

GET https://connect-api.cloud.huawei.com/api/publish/v2/upload-url?appId=XXXXX&suffix=aab

3. Upload file

POST Url obtained from response of step 2

Body:
authCode: Obtained from step 2 response
fileCount: 1
file: <aab file>

4. Submit for review
PUT https://connect-api.cloud.huawei.com/api/publish/v2/app-file-info?appId=XXXX

Send headers in 2 & 4 API:

client_id: <client_Id>
Authorization: Bearer <TOKEN RECEIVED FROM FIRST API>

**Comment by shr3jn** [comment]
@coldfish @minkiapps please check the APIs

**Comment by minkiapps** [comment]
okay, I managed to upload an aab successfully

what I did:
1. https://connect-api.cloud.huawei.com/api/oauth2/v1/token
2. https://connect-api.cloud.huawei.com/api/publish/v2/upload-url?appId=XXXXX&suffix=aab
3. 
```
curl --location --request POST 'https://developerfile7.hicloud.com:443/FileServer/uploadFile' \
--form 'file=@/Users/mingkangpan/Downloads/app-release.aab' \
--form 'authCode=32845763482562387465783246587324653472856' \
--form 'fileCount=1' \
--form 'parseType=1'
```

returns
```
{
    "result": {
        "UploadFileRsp": {
            "fileInfoList": [
                {
                    "fileDestUlr": "https://developerfile7.hicloud.com/FileServer/getFile/7/appAttachtemp/20201012/appAttach/024/290/643/5190043000024290643.20201012145758.96370360574131776279099392887261:20201012151131:2500:E59018A29DA03CAB96731BD13D43741F40BF7F8C13B41C3DC642DF9307F4EDC0.aab",
                    "size": 5704623
                }
            ],
            "ifSuccess": 1
        },
        "resultCode": "0"
    }
}
```

works on my machine ¯\_(ツ)_/¯

**Comment by shr3jn** [comment]
@minkiapps it works fine till step 3. Try step 4, thats the point where its failing on mine.

**Comment by shr3jn** [comment]
I gave it a look again and the thing that I was missing was, while saving app information you need to specify filename. I was specifying the filename with .apk format which was causing the issue. Fixing it and release a new version with aab upload.

**Comment by minkiapps** [comment]
```
curl --location --request PUT 'https://connect-api.cloud.huawei.com/api/publish/v2/app-file-info?appId=102637893' \
--header 'client_id: 182394567832456' \
--header 'Authorization: Bearer hgdfjdghfjehwfkjwe98342579283457ijdfhewhfiuewhf' \
--header 'Content-Type: application/json' \
--data-raw '{
	"fileType": 5,
	"files": [{
		"fileDestUrl": "https://developerfile7.hicloud.com/FileServer/getFile/7/appAttachtemp/20201013/appAttach/024/290/643/5190043000024290643.20201013074328.62726322445985564414278819748672:20201013074352:2500:A6D61EC4F7D8D3228231F00F5CE99B6845FE51A64F273418C7E12F7EE6C829A3.aab",
		"fileName": "app-release.aab"
	}]
}'
```

okay I also managed to get a success response

btw, some questions for clarification @shr3jn :
1. Is this parameter "submit_for_review" in your README even used somewhere? 
2. Since App Gallery has no internal/alpha/beta track, I assume we straight will upload aab and submit for review?
3. Have you found out how to update the release note? ("What's new" field in AG console)

**Comment by shr3jn** [comment]
@minkiapps yes, i guess changelog is not used right now, will see if this can be added to release note. Will check and let you know.

**Comment by shr3jn** [comment]
v1.0.13 released with aab support, on your lane just add the following:

is_aab: true 

you can specify the path to aab on file on "apk_path".

Check readme for example. Also, fileType issue has been resolved.

**Comment by minkiapps** [comment]
what about _submit_for_review_ flag?

**Comment by shr3jn** [comment]
> what about _submit_for_review_ flag?

I had tested this on a separate branch, didn't merge it. But deleted that branch too today, let me check if i have it on my local machine, if so will merge and release a new version.

**Comment by lefloh** [comment]
Seems like introducing the `submit_for_review` flag changed the default behaviour of the plugin from upload to automatically publish. I don't think that this is a good idea. Developers will automatically publish internal testing versions without even knowing it.

**Comment by shr3jn** [comment]
@lefloh submit_for_review flag was already there before this update.

**Comment by lefloh** [comment]
That's strange. We used the plugin for a while but the app was never immediately released. After the upgrade from `v1.0.8` to `v1.0.14` the app was directly published. Adding `submit_for_review: false` fixed it.
