### ISSUE TITLE
Unknown method 'user_error'

### ISSUE THREAD

**Issue by rimzici** [shr3jn/fastlane-plugin-huawei_appgallery_connect#18]
fastlane-plugin-huawei_appgallery_connect v1.0.11

```
Unknown method 'user_error', supported [:user_error!, :command_output, :content_error, :crash!, :not_implemented, :important, :verbose, :shell_error!, :success, :build_failure!, :confirm, :test_failure!, :abort_with_message!, :select, :command, :error, :deprecated, :interactive?, :password, :input, :message, :header]
````

[This merge](https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/commit/1fdf911de974b3d051713bcd4559dd6001334720) seem to have changed `UI.user_error!` to `UI.user_error`, which is causing the issue!

**Comment by shr3jn** [comment]
reverted. use 1.0.12
