### ISSUE TITLE
Add state for release by phase 

### ISSUE THREAD

**Issue by KevinKoenigNormal** [shr3jn/fastlane-plugin-huawei_appgallery_connect#2]
Dear Shr3jn, 

Thanks for your last commit. Can you add the state option to the fastlane option? 

● SUSPEND: suspended
● RELEASE: released
https://developer.huawei.com/consumer/en/service/hms/catalog/AGCConnectAPI.html?page=hmssdk_appGalleryConnect_api_reference_update_phasedrelease_V2

and can you set the other parameters for example startdate, enddate, description, percent to optional

Thank you very much for your excellent work.  (Y)

**Comment by shr3jn** [comment]
@KevinKoenigNormal If we set to phase release, it's compulsory to set startdate, enddate, description, percent.

**Comment by shr3jn** [comment]
If you initially release on entire network you cannot change to phase wise release by updating the release.
