### ISSUE TITLE
Getting {"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [Dist country is required.]"}}

### ISSUE THREAD

**Issue by kurmasan** [shr3jn/fastlane-plugin-huawei_appgallery_connect#22]
Plugin works great to the point when I want to automatically send app for review. As you can see in the logs below app passes up to submitting app for review step, where I'm getting error:

{"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [Dist country is required.]"}}

My lane description:
desc "Submit a new Build to AppGallery TEST"
  lane :deploy_agc do
    # Build and push to test
    sh "cd ./../.. && flutter clean && flutter build apk -t lib/main.dart"
    huawei_appgallery_connect(
        client_id: "MY_CLIENT_ID",
        client_secret: "MY_CLIENT_SECRET",
        app_id: "MY_APP_ID",
        apk_path: "../build/app/outputs/apk/tst/release/app-tst-release.apk",

        submit_for_review: true,
    )
  end

Logs:
[14:54:26]: ---------------------------------------
[14:54:26]: --- Step: huawei_appgallery_connect ---
[14:54:26]: ---------------------------------------
[14:54:26]: Fetching app access token
[14:54:27]: Updating app info
[14:54:29]: Successfully updated app info
[14:54:29]: Fetching upload URL
[14:54:30]: Uploading app
[14:54:41]: Upload app to AppGallery Connect successful
[14:54:41]: Saving app information
[14:54:45]: App information saved.
[14:54:45]: Submitting app for review
+------------------+--------------------+
|             Lane Context              |
+------------------+--------------------+
| DEFAULT_PLATFORM | android            |
| PLATFORM_NAME    | android            |
| LANE_NAME        | android deploy_agc |
+------------------+--------------------+
[14:54:49]: {"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [Dist country is required.]"}}
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | cd ./../.. && flutter clean && flutter build apk  | 169         |
| 💥   | huawei_appgallery_connect                                     | 22          |
+------+---------------------------------------------------------------+-------------+
[14:54:49]: fastlane finished with errors
[!] {"ret"=>{"code"=>204144660, "msg"=>"[cds]submit failed, additional msg is [Dist country is required.]"}}
Running after script...

**Comment by shr3jn** [comment]
Have you set the countries where you want to distribute apps ?

**Comment by kurmasan** [comment]
Yes, i have deployed previous version manually and it's released. When I
enter app form on AppGallery countries are selected.

czw., 14 sty 2021, 07:36 użytkownik Shreejan Shrestha <
notifications@github.com> napisał:

**Comment by kurmasan** [comment]
Well I actually can't believe this. I had chosen languages and I could manually send app for review, but I left language selection form open. In this state you'll get same error as I did. Closing form solves the issue. Thanks, great plugin.

**Comment by Syuenz** [comment]
May I know how you close the form?
