### ISSUE TITLE
changelog_path  not a true change log

### ISSUE THREAD

**Issue by DreamPWJ** [shr3jn/fastlane-plugin-huawei_appgallery_connect#25]
When I use changelog_path the data information is indeed uploaded to the HUAWEI AppGallery, but it is just a comment, not a change record, and the user can't see the information when downloading it

**Comment by DreamPWJ** [comment]
This plugin is very good to use, can you provide other manufacturers' app stores, such as Xiaomi, Oppo, Vivo, Samsumg

**Comment by shr3jn** [comment]
Yes, it's actually a remark field. AGC does not support user changelogs as of today.

**Comment by GeylanKalafMohe** [comment]
Any update on this? When defining the `changelog_path` key I can not see any change in Huawei App Gallery. How to provide changelogs for multiple languages as well?
