### ISSUE TITLE
[Feature Request]Support Open Testing parameter

### ISSUE THREAD

**Issue by MingSern** [shr3jn/fastlane-plugin-huawei_appgallery_connect#27]
The current workaround for deploying to open testing in app gallery is to set the `submit_for_review: false`, which will become a draft, then need to manually set the `Use testing version` to `Yes` as shown in the below image. But i find this to be a bit of a hustle. 

It would be great if this plugin is able to support something like `open_testing: true` parameter or `huawei_appgallery_connect_submit_for_open_testing(...)` to become fully automated.

But of course this is just a request, i have zero idea on how this plugin works and how to implement the idea to support open testing. Amazing plugin btw. Loved it.

![image](https://user-images.githubusercontent.com/40648559/127992995-d3118026-4b9d-4db0-ac53-9608d0776e66.png)

**Comment by MattSkala** [comment]
It would be great, but unfortunately it seems Huawei Connect API currently does not support submitting an app for open testing: https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-submit-0000001158245061

We can watch the release notes and implement it once parameters for open testing become available in the API: https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-pub-releasenotes-0000001111685226

**Comment by shr3jn** [comment]
As @MattSkala mentioned AGC API does not support this right now. So, closing this issue.
