### ISSUE TITLE
Support for Open Testing 

### ISSUE THREAD

**Issue by jan-stoltman-bolt** [shr3jn/fastlane-plugin-huawei_appgallery_connect#29]
Hey! 

Is there any plan to support releases to [Open Testing](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-betatest-release-0000001071228673)? I'd like to achieve something similar to releasing app to Google's alpha/internal users.

**Comment by shr3jn** [comment]
HI! The Huawei AGC Connect API does not expose open testing APIs.
