### ISSUE TITLE
Crash when uploading AAB with `huawei_appgallery_connect`

### ISSUE THREAD

**Issue by adriangl** [shr3jn/fastlane-plugin-huawei_appgallery_connect#31]
Hello!

I've been using the plugin for a long time working without any issue until recently (approximately around November 17th): I found that the `huawei_appgallery_connect` action crashes when uploading an AAB release to AppGallery. Here's the relevant log entries that I found that could be useful to debug the issue:

```
[11:03:39]: Fetching app access token
[11:03:40]: Fetching upload URL
[11:03:40]: Uploading app
[11:03:43]: Upload app to AppGallery Connect successful
[11:03:43]: Saving app information
[11:03:45]: App information saved.
[11:03:45]: Checking aab compilation status
[11:03:45]: Error publishing AAB to HUAWEI AppGallery:
Compilation of aab failed
```

It says that the AAB compilation failed, however I can see in the AppGallery console that the AAB is compiled and a draft app version is created (but not released), so I don't know what the problem is exactly.

Not sure if it could be related, but in the [Connect API Version Changes History](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-pub-releasenotes-0000001111685226), they mention that there have been some API changes on November 16th, so it may be the cause of the errors.

If you need more information about this, please let me know and I'll try to provide it as soon as I can.

Regards

**Comment by ccfiel** [comment]
@adriangl did you solve the problem?

**Comment by adriangl** [comment]
@ccfiel Hi! It seems that it still doesn't work, sadly

**Comment by shr3jn** [comment]
v1.0.17 should fix this issue as well.

**Comment by shr3jn** [comment]
[14:31:42]: ---------------------------------------
[14:31:42]: --- Step: huawei_appgallery_connect ---
[14:31:42]: ---------------------------------------
[14:31:42]: Fetching app access token
[14:31:45]: Fetching upload URL
[14:31:48]: Uploading app
[14:31:52]: Upload app to AppGallery Connect successful
[14:31:52]: Saving app information
[14:31:54]: App information saved.
[14:31:54]: Waiting 10 seconds for upload to get processed...
[14:32:04]: Checking aab compilation status
[14:32:05]: aab file is currently processing, waiting for 2 minutes...
[14:32:15]: Checking aab compilation status
[14:32:15]: aab file is currently processing, waiting for 2 minutes...
[14:32:25]: Checking aab compilation status
[14:32:27]: aab file is currently processing, waiting for 2 minutes...
[14:32:37]: Checking aab compilation status
[14:32:38]: Submitting app for review
[14:32:40]: Successfully submitted app for review

**Comment by kelokchan** [comment]
I'm getting the same error and I have updated the plugin. 

My `Gemfile.lock`
```
    fastlane-plugin-huawei_appgallery_connect (1.0.17)
```

**Comment by adriangl** [comment]
The same thing happened to me too with `1.0.17`, I uploaded an AAB and I can see the following log:
```
[12:01:17]: Fetching app access token
[12:01:18]: Fetching upload URL
[12:01:19]: Uploading app
[12:01:21]: Upload app to AppGallery Connect successful
[12:01:21]: Saving app information
[12:01:22]: App information saved.
[12:01:22]: Waiting 10 seconds for upload to get processed...
[12:01:32]: Checking aab compilation status
[12:01:33]: Compilation of aab failed
```
But the AAB is uploaded properly to AppGallery.

I'm not sure if this is an intermittent issue or maybe the first wait should wait a bit more or something but it keeps happening on my end, sadly

**Comment by f1-shreejan** [comment]
I will make the time parameter configurable. You can see if that helps.

**Comment by bcalik** [comment]
I'm on the v1.0.17 and getting the same error. But it actually submitted successfully.

Here is my fastlane file:

```
  lane :huawei do
    generate_react_native_bundle
    gradle(task: "clean")
    gradle(task: "bundle", build_type: "Release")

    huawei_appgallery_connect(
      client_id: "...",
      client_secret: "...",
      app_id: "...",
      apk_path: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
      is_aab: true,
    )
  end
```

**Comment by shr3jn** [comment]
v1.0.18 release with delay paramter:

`delay_before_submit_for_review: 20 `

increase this value as per your needs (it's in seconds)

@bcalik @adriangl @kelokchan

**Comment by adriangl** [comment]
20 secs delay seemed to do the trick, thanks a lot @shr3jn!

**Comment by Lucia-Bader** [comment]
@adriangl Is this solution still working for you? I'm using v1.0.18 and set the delay before submit for review to 20. At the first try it worked as expected but now I'm getting the same error. I have also tried it with 60 seconds but the error keeps the same.

**Comment by adriangl** [comment]
Hi @Lucia-Bader! I've seen the same result as you this week: the AAB gets uploaded into AppGallery but it doesn't get published, with the `compilation of aab failed` error. I also have the 20 seconds delay set and it was working fine until now, so I don't know what could have happened.

**Comment by adriangl** [comment]
Hello! The issue is still happening currently, should we open a new issue so you can take a look at it @shr3jn?

**Comment by shr3jn** [comment]
Please try again by setting it to a longer interval like 3 minutes or so?

**Comment by adriangl** [comment]
Hello! I tried with 3 minutes and it still gives me the `Compilation of AAB failed` error. Should I try something else?

**Comment by Vall0n** [comment]
Hey @adriangl I've the same issue. For now I disabled the submission to review. Hopefully that will work on our next release....

**Comment by adriangl** [comment]
Still failing here with 6 minutes interval, I'm not sure what's happening with it, could you take a look @shr3jn?

**Comment by shr3jn** [comment]
fixed on v1.0.23. There was changes on huawei's API which was causing the issue.

**Comment by adriangl** [comment]
Thanks a lot @shr3jn! I'll test it today and let you know ;)
I guess we can revert the `delay_before_submit_for_review` to 20 seconds with this change, right?

**Comment by artyorsh** [comment]
> Thanks a lot @shr3jn! I'll test it today and let you know ;) I guess we can revert the `delay_before_submit_for_review` to 20 seconds with this change, right?

I was in progress of integrating this step in our build pipeline and stuck into this issue, so:
- `delay_before_submit_for_review` with magic value of `20` is still needed in latest (1.0.23) version
- You can solve that also with skipping the submission for the review step with `submit_for_review: false`. Though this option will require manual submission, it's still more reliable
