### ISSUE TITLE
The package is being compiled, please try again in 3-5 minutes

### ISSUE THREAD

**Issue by ccfiel** [shr3jn/fastlane-plugin-huawei_appgallery_connect#32]
I got this error

```
[03:05:39]: {"ret"=>{"code"=>204144727, "msg"=>"[AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes"}}
```
same with this https://github.com/cianru/huawei-publish-gradle-plugin/issues/32 but they already fix it there package. How can we resolve this issue? :) Thanks in advance!

**Comment by lazarohcm** [comment]
Had the same issue. Not sure what causes it

**Comment by f1-shreejan** [comment]
@ccfiel @lazarohcm Please use this property to delay the submission:

delay_before_submit_for_review: 20

the time is on seconds

**Comment by lazarohcm** [comment]
Thanks, I'll try that
