### ISSUE TITLE
Automate Testing release build 

### ISSUE THREAD

**Issue by hmedat** [shr3jn/fastlane-plugin-huawei_appgallery_connect#33]
Is there any option to create open testing build and fill all related fields?

![Screen Shot 2022-03-29 at 2 40 05 PM](https://user-images.githubusercontent.com/4534097/160593967-c37818f0-da9f-4f29-95cf-18f045c5fde3.png)

**Comment by shr3jn** [comment]
No, the AGC API does not support this.
