### ISSUE TITLE
{"ret"=>{"code"=>204144727, "msg"=>"[AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes"}}

### ISSUE THREAD

**Issue by anthony3444** [shr3jn/fastlane-plugin-huawei_appgallery_connect#34]
Hi guys!

Thanks for your great plugin! Since couple of weeks, this error appears during the deployment of App:

`{"ret"=>{"code"=>204144727, "msg"=>"[AppGalleryConnectPublishService]The package is being compiled, please try again in 3-5 minutes"}}`

In last October, when I use my fastlane, all was great. Is there any no-regression in your plugin?

Thank you very much!

**Comment by anthony3444** [comment]
Hi,

Thanks for your reply. However there was no change with this additional parameter. The error is already present.

Here you are the call:

         huawei_appgallery_connect(
                client_id: options[:CLIENT_ID_HUAWEI],
                client_secret: options[:CLIENT_SECRET_HUAWEI],
                app_id: options[:APP_ID_HUAWEI],                
                apk_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
                # if you're uploading aab instead of apk, specify is_aab to true and specify path to aab file on apk_path
                is_aab: is_bundle,
                
                # Optional, Parameter beyond this are optional
                                
                submit_for_review: true,
                # Delay for the submission as the package needs to compile on Huawei servers (in seconds)
                delay_before_submit_for_review: 50
            
                #privacy_policy_url: "https://example.com",
                #changelog_path: metadata_path_android + "appgallery.txt"
            
                # release time to release app on specific date
               # release_time: "2019-12-25T07:05:15+0000",
            
                # For phase wise release: set these parameters
                #phase_wise_release: true,
                #phase_release_start_time: "2019-12-25T07:05:15+0000",
                #phase_release_end_time: "2019-12-28T07:05:15+0000",
                #phase_release_percent: "10.00",
                #phase_release_description: "<DESCRIPTION>"
            )

**Comment by shr3jn** [comment]
set the delay parameter to 300 or higher (~5 mins or higher)

**Comment by anthony3444** [comment]
I tried 180 without effect. I will try with 300. Thanks
