### ISSUE TITLE
[FEATURE] Upload screenshots/icons

### ISSUE THREAD

**Issue by vogloblinsky** [shr3jn/fastlane-plugin-huawei_appgallery_connect#43]
Using this API : https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-file-info-0000001111685202

I will check if i have time to do a PR

**Comment by shr3jn** [comment]
Ok I will see if this can be planned.

**Comment by shr3jn** [comment]
When uploading image through the upload URL, the following error response is observed:
Tried with JPG/PNG and size < 2MB as said on docs.
{
    "result": {
        "CException": {
            "errorCode": 77720022,
            "errorDesc": "image type can't match"
        },
        "resultCode": "77720022"
    }
}
