### ISSUE TITLE
`changelog_path` key not uploading change log?

### ISSUE THREAD

**Issue by GeylanKalafMohe** [shr3jn/fastlane-plugin-huawei_appgallery_connect#48]
When defining the `changelog_path` key I can not see any change in Huawei App Gallery. How to provide changelogs for multiple languages as well?

How does that file look like?

**Comment by shr3jn** [comment]
Are you providing the correct path to the changelog file?

**Comment by shr3jn** [comment]
it looks like the remark paramter that the API is consuming is being used as review information.

**Comment by shr3jn** [comment]
I don't see any API to upload the changelogs on AGC. Please let me know if you find the API. Closing ticket for now.

**Comment by GeylanKalafMohe** [comment]
Here is the API to provide all important informations about an app including the changelogs and app description. Kindly add these to the fastlane plugin:

https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-app-info-query-0000001158365045

**Comment by GeylanKalafMohe** [comment]
The changelogs and app metadata should overlap with Android Default structure of providing the metadata for fastlane.

I.e. fastlane/metadata/en-US/full-deacription.txt

And so on. Check running `fastlane init` in a flutter project.

**Comment by GeylanKalafMohe** [comment]
You actually already have the action defined in your plugin but you didn't mention it in your README.md

I will update it and make a pull request
