### ISSUE TITLE
Require 'CGI' introduce error

### ISSUE THREAD

**Issue by UladzislauListapadEF** [shr3jn/fastlane-plugin-huawei_appgallery_connect#50]
I have this error in 1.0.24. (Error loading plugin 'fastlane-plugin-huawei_appgallery_connect': cannot load such file -- CGI)

I suppose you need to change `require 'CGI'` to `require 'cgi'`

**Comment by shr3jn** [comment]
i've added CGI dependency on v1.0.25 please give it a test

**Comment by shr3jn** [comment]
which docker image are you using?

**Comment by UladzislauListapadEF** [comment]
ubuntu 22.04

**Comment by RIvannikov** [comment]
[08:24:29]: Error loading plugin 'fastlane-plugin-huawei_appgallery_connect': cannot load such file -- CGI

**Comment by mediabc** [comment]
I was sent a pull request with fix: https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/pull/51

Please mergi it @shr3jn
