### ISSUE TITLE
Support for "GMS devices only"

### ISSUE THREAD

**Issue by cagdassozer** [shr3jn/fastlane-plugin-huawei_appgallery_connect#54]
We're actively using the plugin, thanks for all the works you've done. Is it possible to add this support to the plugin ? 

https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-gms-0000001111845094

I really don't understand this API call, actually while publishing the release application, we always need to select "gms-devices-only" option. I would expect to see this parameter in the submitting-app api call. 

Can you share your ideas about it ? Thanks a lot

**Comment by shr3jn** [comment]
Release v1.0.28:

To update the GMS dependency of the app, use the following action

huawei_appgallery_connect_update_app_localization(
    client_id: "<CLIENT_ID>",
    client_secret: "<CLIENT_SECRET>",
    app_id: "<APP_ID>",
    gms_dependency: 1 #Indicates whether an app depends on GMS. 1: Yes, 0: No
)

**Comment by cagdassozer** [comment]
Appreciated for your new version 🙏
