### ISSUE TITLE
app's packages exceeds the upper limit

### ISSUE THREAD

**Issue by hebadarweesh1** [shr3jn/fastlane-plugin-huawei_appgallery_connect#57]
```
gradle(
    task: 'bundle',
    build_type: getDistConfiguration(),
    print_command: true,
    print_command_output:true,
    properties: androidSigning()
)

```
```
huawei_appgallery_connect(
    client_id: ****,
    client_secret:*****,
    app_id: *****,
    apk_path: Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],  
    is_aab: true,
    submit_for_review: false,
)
```

i get an error {"ret"=>{"code"=>204144662, "msg"=>"[cds]add apk failed, additional msg is [the app's packages exceeds the upper limit.]"}}. 

I am not sure how it shows apk failed while i am uploading an aab. also i uploaded the same aab to play store and it is working fine.

**Comment by shr3jn** [comment]
Please refer to the following size limit as per: https://developer.huawei.com/consumer/en/doc/agcapi-file-requirement
RPK: up to 20 MB; 
APK: up tp 4 GB; 
AAB: up to 150 MB. 

Make sure your package is below the limits.

**Comment by hebadarweesh1** [comment]
i just realized what is the issue, the number of packages (aab bundles) uploaded to Huawei app gallery were 300 bundle (which i believe is the max number) so i had to delete old packages to be able to upload a new one.

**Comment by PhilippKolmann** [comment]
@hebadarweesh1 we have faced the same issue...

Have you found a way to remove older packages during fastlane upload of a new package?
