### ISSUE TITLE
1.0.29 error: upload_app undefined method

### ISSUE THREAD

**Issue by sposs** [shr3jn/fastlane-plugin-huawei_appgallery_connect#64]
/2.7.0/gems/fastlane-plugin-huawei_appgallery_connect-1.0.29/lib/fastlane/plugin/huawei_appgallery_connect/helper/huawei_appgallery_connect_helper.rb:143:in `upload_app': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)

**Comment by shr3jn** [comment]
Added error handling on 1.0.30. Should show the actual error now.
