### ISSUE TITLE
1.0.30 Error: [AppGalleryConnectPublishService]input aab size is too large

### ISSUE THREAD

**Issue by Ornaiim** [shr3jn/fastlane-plugin-huawei_appgallery_connect#65]
Hi there,

While we have successfully been able to deploy our app bundle to the AppGallery for several months now, we now face this issue with version 1.0.30:

`{"ret":{"code":204144641,"msg":"[AppGalleryConnectPublishService]input aab size is too large"}}`

We are able to upload the .aab file to the AppGallery manually through the AppGallery Connect web page, so it seems the size of the package is not an issue.

Thanks for the help!

**Comment by shr3jn** [comment]
@Ornaiim what is the size of your aab?

File size restrictions:
APK file: The size cannot exceed 4 GB.
RPK file: The size cannot exceed 20 MB.
AAB file: The size cannot exceed 150 MB.
APP file (HarmonyOS app): The size cannot exceed 4 GB.
EXE file (PC app): The size cannot exceed 4 GB.

https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-upload-file-new-0000001111845090

**Comment by Ornaiim** [comment]
Thanks for your answer.

Our AAB package is indeed larger than the limit, however it has never been an issue until now.
Would that be possible Huawei added new restrictions recently?

**Comment by shr3jn** [comment]
yes they may have introduced the new restrictions.
