### ISSUE TITLE
[AppGalleryConnectFileService]distContryList is empty and usage route site is not China.]

### ISSUE THREAD

**Issue by dzengi-com** [shr3jn/fastlane-plugin-huawei_appgallery_connect#66]
```
huawei_appgallery_connect(
    client_id: client_id,
    client_secret: client_secret,
    app_id: app_id,
    apk_path: File.join(Dir.pwd, "../android/app/build/outputs/bundle/release", "app-release.aab"),

    is_aab: true,
    submit_for_review: true,
    delay_before_submit_for_review: 60,
)
```

`{"ret":{"code":204144694,"msg":"[cfs] get siteId failed, additional msg is [[AppGalleryConnectFileService]distContryList is empty and usage route site is not China.]"}}`

I found the [issue](https://docs.appcircle.io/account/my-organization/api-integrations/adding-huawei-api-key), and in my account I selected all (199) countries except China. But I still get this error

**Comment by shr3jn** [comment]
Hi @dzengi-com, this error you're receiving is from AGC so you may get solution if you post this on AGC community.

https://forums.developer.huawei.com/forumPortal/en/forum/events

**Comment by dzengi-com** [comment]
@shr3jn Yes, and I received an answer from one of the developers that I should pass a list of countries and this needs to be implemented in the plugin. What do you think?

**Comment by shr3jn** [comment]
@dzengi-com  on which API should the country list be passed?

**Comment by dzengi-com** [comment]
Well, apparently in one of the APIs that uses this plugin

**Comment by shr3jn** [comment]
Please provide link to your post on AGC forum.

**Comment by dzengi-com** [comment]
I don't have a link, it was a private conversation

**Comment by shr3jn** [comment]
If you have a link to the documentation on which API should the country param be passed, let me know.

**Comment by dzengi-com** [comment]
Could you share api calls which does this plugin use?

**Comment by arnovanzyl** [comment]
I'm also running into the same issue here :/

[!] {"ret":{"code":204144694,"msg":"[cfs] get siteId failed, additional msg is [[AppGalleryConnectFileService]distContryList is empty and usage route site is not China.]"}}

**Comment by arnovanzyl** [comment]
Did someone manage to solve this?

**Comment by dzengi-com** [comment]
@shr3jn Why did you close this issue? It is relevant and 100% reproducible

**Comment by shr3jn** [comment]
okay i will check once.

**Comment by famasf1** [comment]
> I don't have a link, it was a private conversation

Can you ask which API they are talking about specifically? I forked the repo and tried adding 'publishCountry' from this [API](https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-app-info-update-0000001111685198) but had no luck.

**Comment by dzengi-com** [comment]
> > I don't have a link, it was a private conversation
> 
> Can you ask them which API they are talking about specifically? I forked the repo and tried adding 'publishCountry' from this [Publishing API](https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-app-info-update-0000001111685198) but had no luck. And i couldn't find any reference about adding countries anywhere else.

I haven't looked into exactly what methods this plugin calls. Since they are falling, it means that countries also need to be added to parameters

**Comment by famasf1** [comment]
> > > I don't have a link, it was a private conversation
> > 
> > 
> > Can you ask them which API they are talking about specifically? I forked the repo and tried adding 'publishCountry' from this [Publishing API](https://developer.huawei.com/consumer/en/doc/AppGallery-connect-References/agcapi-app-info-update-0000001111685198) but had no luck. And i couldn't find any reference about adding countries anywhere else.
> 
> I haven't looked into exactly what methods this plugin calls. Since they are falling, it means that countries also need to be added to parameters

i assume this plugin use publishing API since it had parameter for `privacy_policy_url` and it's the only API i found that have anything related to country. So i forked this repo and put in a new parameter inside and attempted to run CI with my own app.

I added the following line into `huawei_appgallery_connect_action.rb`

this is inside `self.run`

```
if params[:privacy_policy_url] != nil
            if params[:publish_country] != nil
              Helper::HuaweiAppgalleryConnectHelper.update_appinfo(params[:client_id], token, params[:app_id], params[:privacy_policy_url], params[:publish_country])
            else
              Helper::HuaweiAppgalleryConnectHelper.update_appinfo(params[:client_id], token, params[:app_id], params[:privacy_policy_url], 'US, OTHER') #according to docs, OTHER cannot be the only parameter. Default to US.
            end
          end
```

this is inside `self.available_options`

```
FastlaneCore::ConfigItem.new(key: :publish_country,
                                                  env_name: "HUAWEI_APPGALLERY_PUBLISH_COUNTRY",
                                                  description: "Country code for the country where the app is published",
                                                  optional: true,
                                                  type: String)
```

then add a new parameter and editing json encoding inside `huawei_appgallery_connect_helper.rb`

```
def self.update_appinfo(client_id, token, app_id, privacy_policy_url, publish_country)
        UI.important("Updating app info")

        uri = URI.parse("https://connect-api.cloud.huawei.com/api/publish/v2/app-info?appId=#{app_id}")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        request = Net::HTTP::Put.new(uri.request_uri)
        request["client_id"] = client_id
        request["Authorization"] = "Bearer #{token}"
        request["Content-Type"] = "application/json"

        request.body = {privacyPolicy: privacy_policy_url, publishCountry: publish_country}.to_json

        response = http.request(request)
        if !response.kind_of? Net::HTTPSuccess
          UI.user_error!("Cannot update app info, please check API Token / Permissions (status code: #{response.code})")
          return false
        end
        result_json = JSON.parse(response.body)

        if result_json['ret']['code'] == 0
          UI.success("Successfully updated app info")
        else
          UI.user_error!(result_json)
          UI.user_error!("Failed to update app info")
        end
      end
```
I'm not sure if i edited the wrong methods because i still got the same error. Feel free to dive into my fork [here.](https://github.com/famasf1/fastlane-plugin-huawei_appgallery_connect.git) That's why i want to know specifically which API did the Huawei developer is talking about.

**Comment by dzengi-com** [comment]
> Did someone manage to solve this?

No. This issue is still relevant. The library has not been updated since May

**Comment by Daha62** [comment]
same thing
